# Generated by Django 5.2.7 on 2025-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcartposition',
            constraint=models.UniqueConstraint(fields=('cart', 'item'), name='unique_item'),
        ),
    ]
