# Generated by Django 5.2.7 on 2025-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_last_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
