# Generated by Django 5.2.7 on 2025-11-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_clip_clipdislike_cliplike_delete_post_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='clipdislike',
            name='clip',
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ClipLike',
        ),
        migrations.DeleteModel(
            name='Clip',
        ),
        migrations.DeleteModel(
            name='ClipDislike',
        ),
    ]
